name: Jacoco Unit tests CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build Jacoco report
        run: mvn clean jacoco:prepare-agent install jacoco:report
      - name: publish report
        run: bash <(curl -s https://codecov.io/bash) # Upload to Codecov
